# Files distributed to students (.ok & tests/ handled automatically)
sp20/hw/hw02.d: $(MATERIALS_DST)/sp20/hw/hw02/president_births.csv
sp20/hw/hw02.d: $(MATERIALS_DST)/sp20/hw/hw02/temperatures.csv
sp20/hw/hw02.d: $(MATERIALS_DST)/sp20/hw/hw02/world_population.csv
sp20/hw/hw02.d: $(MATERIALS_DST)/sp20/hw/hw02/array_diff.png
sp20/hw/hw02.d: $(MATERIALS_DST)/sp20/hw/hw02/array_cumsum.png
sp20/hw/hw02.d: $(MATERIALS_DST)/sp20/hw/hw02/old_faithful.csv
sp20/hw/hw02.d: $(MATERIALS_DST)/sp20/hw/hw02/inventory.csv
sp20/hw/hw02.d: $(MATERIALS_DST)/sp20/hw/hw02/sales.csv