# Files distributed to students (.ok & tests/ handled automatically)
sp20/lab/lab01.d: $(MATERIALS_DST)/sp20/lab/lab01/error.jpg
sp20/lab/lab01.d: $(MATERIALS_DST)/sp20/lab/lab01/numberline_0.png
sp20/lab/lab01.d: $(MATERIALS_DST)/sp20/lab/lab01/numberline_1.png
sp20/lab/lab01.d: $(MATERIALS_DST)/sp20/lab/lab01/map.jpg