# Files distributed to students (.ok & tests/ handled automatically)
sp20/hw/hw09.d: $(MATERIALS_DST)/sp20/hw/hw09/serial_numbers.csv
sp20/hw/hw09.d: $(MATERIALS_DST)/sp20/hw/hw09/smallrephist.png
sp20/hw/hw09.d: $(MATERIALS_DST)/sp20/hw/hw09/reviews.csv
sp20/hw/hw09.d: $(MATERIALS_DST)/sp20/hw/hw09/more_reviews.csv
sp20/hw/hw09.d: $(MATERIALS_DST)/sp20/hw/hw09/one_sample.csv