# Files distributed to students (.ok & tests/ handled automatically)
sp20/project/final_sp20.d: $(MATERIALS_DST)/sp20/project/final_sp20/actors.csv
sp20/project/final_sp20.d: $(MATERIALS_DST)/sp20/project/final_sp20/electricity2017_sample.csv
sp20/project/final_sp20.d: $(MATERIALS_DST)/sp20/project/final_sp20/food_access_2010_2015.csv
sp20/project/final_sp20.d: $(MATERIALS_DST)/sp20/project/final_sp20/states.csv
sp20/project/final_sp20.d: $(MATERIALS_DST)/sp20/project/final_sp20/instagram_sample.csv
sp20/project/final_sp20.d: $(MATERIALS_DST)/sp20/project/final_sp20/the_office.csv
sp20/project/final_sp20.d: $(MATERIALS_DST)/sp20/project/final_sp20/office_wikipedia.csv