# Files distributed to students (.ok & tests/ handled automatically)
sp20/hw/hw03.d: $(MATERIALS_DST)/sp20/hw/hw03/unemployment.csv
sp20/hw/hw03.d: $(MATERIALS_DST)/sp20/hw/hw03/nst-est2016-alldata.csv
sp20/hw/hw03.d: $(MATERIALS_DST)/sp20/hw/hw03/scatter.png
sp20/hw/hw03.d: $(MATERIALS_DST)/sp20/hw/hw03/var1.png
sp20/hw/hw03.d: $(MATERIALS_DST)/sp20/hw/hw03/var2.png
sp20/hw/hw03.d: $(MATERIALS_DST)/sp20/hw/hw03/boston.csv
sp20/hw/hw03.d: $(MATERIALS_DST)/sp20/hw/hw03/manila.csv