# Files distributed to students (.ok & tests/ handled automatically)
sp20/lab/lab05.d: $(MATERIALS_DST)/sp20/lab/lab05/Austen_PrideAndPrejudice.txt
sp20/lab/lab05.d: $(MATERIALS_DST)/sp20/lab/lab05/player_data.csv
sp20/lab/lab05.d: $(MATERIALS_DST)/sp20/lab/lab05/salary_data.csv
sp20/lab/lab05.d: $(MATERIALS_DST)/sp20/lab/lab05/small_srswor_salary.csv
sp20/lab/lab05.d: $(MATERIALS_DST)/sp20/lab/lab05/large_srswor_salary.csv
sp20/lab/lab05.d: $(MATERIALS_DST)/sp20/lab/lab05/comparisons.png
sp20/lab/lab05.d: $(MATERIALS_DST)/sp20/lab/lab05/nacho_reactions.png