# Files distributed to students (.ok & tests/ handled automatically)
sp20/hw/hw04.d: $(MATERIALS_DST)/sp20/hw/hw04/burrito.csv
sp20/hw/hw04.d: $(MATERIALS_DST)/sp20/hw/hw04/burritos_types.csv
sp20/hw/hw04.d: $(MATERIALS_DST)/sp20/hw/hw04/ratings.csv
sp20/hw/hw04.d: $(MATERIALS_DST)/sp20/hw/hw04/faculty.csv
sp20/hw/hw04.d: $(MATERIALS_DST)/sp20/hw/hw04/berkeley_faculty.csv