# Files distributed to students (.ok & tests/ handled automatically)
sp20/lab/lab03.d: $(MATERIALS_DST)/sp20/lab/lab03/world_population.csv
sp20/lab/lab03.d: $(MATERIALS_DST)/sp20/lab/lab03/array_logarithm.jpg
sp20/lab/lab03.d: $(MATERIALS_DST)/sp20/lab/lab03/array_multiplication.jpg
sp20/lab/lab03.d: $(MATERIALS_DST)/sp20/lab/lab03/more_restaurant_bills.csv
sp20/lab/lab03.d: $(MATERIALS_DST)/sp20/lab/lab03/excel_array.jpg
sp20/lab/lab03.d: $(MATERIALS_DST)/sp20/lab/lab03/chaining_method_calls.png
sp20/lab/lab03.d: $(MATERIALS_DST)/sp20/lab/lab03/imdb.csv