# Files distributed to students (.ok & tests/ handled automatically)
sp20/lab/lab04.d: $(MATERIALS_DST)/sp20/lab/lab04/raw_compensation.csv
sp20/lab/lab04.d: $(MATERIALS_DST)/sp20/lab/lab04/movies_by_year.csv
sp20/lab/lab04.d: $(MATERIALS_DST)/sp20/lab/lab04/apply.png