# Files distributed to students (.ok & tests/ handled automatically)
sp20/hw/hw06.d: $(MATERIALS_DST)/sp20/hw/hw06/player_data.csv
sp20/hw/hw06.d: $(MATERIALS_DST)/sp20/hw/hw06/salary_data.csv
sp20/hw/hw06.d: $(MATERIALS_DST)/sp20/hw/hw06/sample_salary_data.csv
sp20/hw/hw06.d: $(MATERIALS_DST)/sp20/hw/hw06/earthquakes_2019.csv